modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="enchantedmoon"
version="0.1"
displayName="EnchantedMoon"
credits="Created using my brain"
displayURL="https://discord.gg/KkftTDKaAm"
logoFile="logo.png"
authors="Kuroshi23"
description="Описание я пока что не придумал так что придумайте за меня"

[[dependencies.enchantedmoon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.enchantedmoon]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enchantedmoon]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

